version: 0.0
os: linux
files:
  - source: /
    destination: /var/app/current

hooks:
  BeforeInstall:
    - location: /set_env_vars.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: /start_application.sh
      timeout: 300
      runas: ubuntu